# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_reqs', '0006_auto_20171204_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passreqs',
            name='website',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
